name: 'Setup Android tools'
author: 'Maxim Lobanov'
description: 'Set up Android tools in GitHub Actions workflow with caching'
inputs:
  packages:
    description: 'Packages to install'
    required: true
  cache:
    description: 'Enable caching'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'yellow'
