name: Build task
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: 0 0 * * *

jobs:
  Build:
    name: Build task
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.operating-system }}
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Node.JS
      uses: actions/setup-node@master
      with:
        node-version: 16

    - name: npm install
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm run test

    - name: Lint
      run: npm run lint
